// <auto-generated />
using System;
using CurriculumAnalyzer.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurriculumAnalyzer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331202103_SyncProduction")]
    partial class SyncProduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.AnalysisEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActionPlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurriculumId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedMaxSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedMinSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("JobRecommendationsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpportunitiesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("RawGrokResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SectionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaknessesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDate");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.CurriculumEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketObjective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TargetSalary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.AnalysisEntity", b =>
                {
                    b.HasOne("CurriculumAnalyzer.API.Data.Entities.CurriculumEntity", "Curriculum")
                        .WithMany("Analyses")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.CurriculumEntity", b =>
                {
                    b.HasOne("CurriculumAnalyzer.API.Data.Entities.UserEntity", "User")
                        .WithMany("Curriculums")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.CurriculumEntity", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("CurriculumAnalyzer.API.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Curriculums");
                });
#pragma warning restore 612, 618
        }
    }
}
